language: go

env:
  - GO111MODULE=on
  - GOFLAGS='-mod vendor'

go:
  - 1.12.x
  - tip

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

install: true

notifications:
  email: false

script:
  - go build ./...
